import { describe, expect, it } from 'vitest'
import { AGENT_NAME_POOL } from './agentIdentity'

describe('AGENT_NAME_POOL', () => {
  it('uses the bespoke nickname pool for fallback subagent identities', () => {
    expect(AGENT_NAME_POOL).toEqual([
      'Donny-Davis',
      'Harmonium',
      'Jenkinz',
      'Dexterman',
      'Croxley-Marvin',
      'Wendens-Ambo',
      'Georgioni',
      'Teleminster',
      'Korbis',
      'Wellson',
      'Baxter-Ravens',
      'Brian Brian Brian',
      'Imhotep',
      'Hubert Cumberdale',
      'Phobos',
      'Deimos',
      'Dogsbody',
      'Roboteknik',
      'Zandar',
      'Serafin',
      'Orzwald',
      'Channing',
      'Tobus Maximus',
      'Arxfold',
      'Persia',
      'Jakker',
      'Hilbert',
      'Dufus',
      'Sicklemas',
      'Frankenborg',
      'Chaxim',
      'Tre Solomon',
      'Eloque',
      'Xarxes',
      'Julio',
      'Jeremy Patchman',
      'Malek Malloc',
      'Tommy Tipper',
      'Jim The Mage',
      'Kevin The Karate King',
      'Master Maxwell',
      'Dorribald',
      'Marsham',
      'Yorris',
      'Bennison',
      'La Li Lu Le Lo',
      'Nish',
      'Ozbern',
      'Pendris',
      'Quendrew',
      'Roobis',
      'Uno',
      'Volkarr',
      'Yoodoo'
    ])
  })
})
